### PR TITLE
Version 16

### PR DESCRIPTION
**Pull request by erbg**
Actually the tools seems to have problem with SQL Server 2022. I added the version numbers (i hope i havn't forgot somewhere)

### CODE REVIEW

**Review by molekamp — APPROVED** [review]
I would also want this change. Please merge this.

**Comment by DrJohnT** [comment]
@molekamp  would you be able to take over this project from me?  In recent years I never seem to get the time to dedicate to this project and I hate to be the bottleneck stopping the extension from progressing.

If agreeable to you, I will figure out how the extension can be published on Microost Visual Studio Marketplace by yourself or anyone else interested in taking the project over.

**Comment by DrJohnT** [comment]
@erbg  would you be able to take over this project from me?  In recent years I never seem to get the time to dedicate to this project and I hate to be the bottleneck stopping the extension from progressing.

If agreeable to you, I will figure out how the extension can be published on Microost Visual Studio Marketplace by yourself or anyone else interested in taking the project over.

**Comment by molekamp** [comment]
Hello John,

As I also have a full time job, I wouldn't want to raise expectations that
I cannot meet. However, I would be interested to help out in minor updates
(like the version 16 you added) to the DeployCube project, and to publish
these to PowerShell Gallery. I will need some help and guidance from you to
do this though.

Also, I hadn't even realized that there was also an Azure DevOps extension
that leverages the PowerShell project. I was using the PowerShell module
directly in my yaml pipeline. I only found the
AzureDevOpsExtensionsForSqlServer
<https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer> project
because I noticed a recent commit to it on your profile, and then I linked
it to "publishing an extension to the marketplace" which you mentioned
above.
If this extension can be used in a yaml pipeline (the examples only seem to
be for classic release pipelines) then it would also be of interest to me,
and (again with some help from you) I would be able to make minor changes
and publish them to VS Marketplace.

To take things step by step, if you're willing to help me, I would like to
start first on the DeployCube project and see how things go from there.

Regards,
Erik


Op vr 7 jun 2024 om 13:36 schreef Dr John Tunnicliffe <
***@***.***>:

**Pull request merged**
